### ISSUE TITLE
Add logo to Facebook login

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/fondfolio#52]
https://www.facebook.com/settings?tab=applications

<img width="770" alt="Screen Shot 2020-04-18 at 2 46 20 AM" src="https://user-images.githubusercontent.com/462077/79630409-03721980-811f-11ea-8d55-4a48f85e2dee.png">

**Comment by feeohnah** [comment]
done https://www.facebook.com/settings?tab=applications
