### ISSUE TITLE
Center and give the header a max width

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/fondfolio#53]
<img width="2518" alt="Screen Shot 2020-05-05 at 4 30 53 PM" src="https://user-images.githubusercontent.com/462077/81113204-d929a580-8eed-11ea-8a29-5bf5dc853f9b.png">

Add the following to header, use a different max-width though

```css
max-width: 1000px;
left: 50%;
transform: translate(-50%, 0);
```

**Comment by feeohnah** [comment]
fixed 89b48cbd4fcf3ccc8310433aee9fa25548768441
