### ISSUE TITLE
Blog page has javascript error

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/fondfolio#55]
<img width="540" alt="Screen Shot 2020-05-05 at 4 35 26 PM" src="https://user-images.githubusercontent.com/462077/81113619-8ac8d680-8eee-11ea-80c7-1ecffe1c96c3.png">

Likely existed since the instagram feed was added. needs an existence check before initiating the instagram feed.

**Comment by feeohnah** [comment]
Fixed in d738b2278231ed4cc2ddc9aeec143cd295e6dd7a
